"""Create the full database schema on the active database (respects USE_CLOUD_DB).

Why this exists: the Alembic initial migration was autogenerated for SQLite,
which tolerates forward foreign-key references and cyclic FKs at CREATE TABLE
time. Postgres does not. ``SQLModel.metadata.create_all`` computes the correct
dependency order and emits the cyclic ``payments <-> receipt_uploads`` FK via a
follow-up ALTER, so it works on both engines.

Usage (from backend/):
    .venv/bin/python -m scripts.init_cloud_schema           # create tables
    .venv/bin/python -m scripts.init_cloud_schema --reset   # drop all first

After running, mark migrations as applied so future ``alembic upgrade`` works:
    .venv/bin/alembic stamp head
"""

from __future__ import annotations

import asyncio
import sys

from sqlalchemy import text

import app.db.base  # noqa: F401  registers every model on SQLModel.metadata
from app.core.config import settings
from app.db.session import engine
from sqlmodel import SQLModel


async def _reset(conn) -> None:
    """Drop the whole public schema (Postgres) or all tables (SQLite)."""
    if settings.is_sqlite:
        await conn.run_sync(SQLModel.metadata.drop_all)
    else:
        # Nukes tables AND leftover ENUM types from the failed migration.
        await conn.execute(text("DROP SCHEMA public CASCADE"))
        await conn.execute(text("CREATE SCHEMA public"))


async def main() -> None:
    reset = "--reset" in sys.argv
    target = "CLOUD (Postgres)" if settings.use_cloud_db else "LOCAL (SQLite)"
    print(f"Target: {target}")

    async with engine.begin() as conn:
        if reset:
            print("Resetting schema (dropping existing objects)...")
            await _reset(conn)
        print("Creating tables...")
        await conn.run_sync(SQLModel.metadata.create_all)

    async with engine.begin() as conn:
        names = sorted(SQLModel.metadata.tables)
    print(f"Done. {len(names)} tables ensured:")
    for n in names:
        print(f"  - {n}")

    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(main())
