"""initial_schema

Revision ID: 2cf868cb9e8a
Revises: 
Create Date: 2026-06-13 16:12:48.435548
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2cf868cb9e8a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actor_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('old_values_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('new_values_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_organization_id'), ['organization_id'], unique=False)

    op.create_table('idempotency_keys',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'FAILED', name='idempotencystatus'), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_keys_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_idempotency_keys_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_idempotency_keys_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_idempotency_keys_status'), ['status'], unique=False)

    op.create_table('organizations',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('accent_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('working_hours', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('saas_tier', sa.Enum('STARTER', 'PRO', 'ENTERPRISE', name='saastier'), nullable=False),
    sa.Column('saas_status', sa.Enum('TRIALING', 'ACTIVE', 'PAST_DUE', 'READ_ONLY', 'SUSPENDED', 'CANCELLED', 'ARCHIVED', name='saasstatus'), nullable=False),
    sa.Column('member_cap', sa.Integer(), nullable=True),
    sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('saas_current_period_end', sa.DateTime(), nullable=True),
    sa.Column('saas_grace_until', sa.DateTime(), nullable=True),
    sa.Column('stripe_connect_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_connect_status', sa.Enum('NONE', 'PENDING', 'ACTIVE', 'RESTRICTED', name='connectstatus'), nullable=False),
    sa.Column('enrollment_mode', sa.Enum('OPEN', 'APPROVED', 'INVITE_ONLY', name='enrollmentmode'), nullable=False),
    sa.Column('gym_status', sa.Enum('OPEN', 'CLOSED', 'HALF_DAY', name='gymstatus'), nullable=False),
    sa.Column('mfa_required', sa.Boolean(), nullable=False),
    sa.Column('require_member_profile', sa.Boolean(), nullable=False),
    sa.Column('checklist_stripe_connected', sa.Boolean(), nullable=False),
    sa.Column('checklist_plan_published', sa.Boolean(), nullable=False),
    sa.Column('checklist_enrollment_configured', sa.Boolean(), nullable=False),
    sa.Column('checklist_staff_invited', sa.Boolean(), nullable=False),
    sa.Column('checklist_office_configured', sa.Boolean(), nullable=False),
    sa.Column('signup_frozen', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_org_code'), ['org_code'], unique=True)

    op.create_table('payments',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('member_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kind', sa.Enum('SAAS_SUBSCRIPTION', 'MEMBER_FEE', 'TRAINER_PAYOUT', name='paymentkind'), nullable=False),
    sa.Column('method', sa.Enum('CARD', 'CASH', 'BANK_TRANSFER', 'MOBILE_WALLET', name='paymentmethod'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED', 'PARTIALLY_REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stripe_payment_intent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_charge_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logged_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('refunded_amount', sa.Float(), nullable=False),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('receipt_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['organization_members.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['membership_plans.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipt_uploads.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_stripe_payment_intent_id'), ['stripe_payment_intent_id'], unique=False)

    op.create_table('receipt_uploads',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('member_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('original_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('processed_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ocr_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extracted_amount', sa.Float(), nullable=True),
    sa.Column('extracted_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extracted_payer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extracted_payee', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extracted_txn_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extracted_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('authenticity_score', sa.Float(), nullable=True),
    sa.Column('perceptual_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('cross_validation_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('flags_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'AUTO_APPROVED', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'REVERSED', name='receiptstatus'), nullable=False),
    sa.Column('auto_approved', sa.Boolean(), nullable=False),
    sa.Column('spot_audit_selected', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('review_action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('review_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('payment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['organization_members.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['membership_plans.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receipt_uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipt_uploads_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipt_uploads_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipt_uploads_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipt_uploads_perceptual_hash'), ['perceptual_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipt_uploads_status'), ['status'], unique=False)

    op.create_table('signup_attempts',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('org_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('suspicious', sa.Boolean(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signup_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signup_attempts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_signup_attempts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signup_attempts_org_code'), ['org_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_signup_attempts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signup_attempts_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('verification_tokens',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purpose', sa.Enum('EMAIL_VERIFY', 'PASSWORD_RESET', 'MAGIC_LINK', 'MEMBER_INVITE', 'MEMBER_ACTIVATION', name='verificationpurpose'), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_tokens_code_hash'), ['code_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_tokens_consumed'), ['consumed'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_tokens_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_tokens_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_tokens_purpose'), ['purpose'], unique=False)

    op.create_table('auth_sessions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('refresh_token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('os', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('remember_device', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_sessions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_sessions_refresh_token_hash'), ['refresh_token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_sessions_revoked'), ['revoked'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('cash_reconciliations',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('system_total', sa.Float(), nullable=False),
    sa.Column('counted_total', sa.Float(), nullable=False),
    sa.Column('discrepancy', sa.Float(), nullable=False),
    sa.Column('performed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_reconciliations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_reconciliations_business_date'), ['business_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_reconciliations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_reconciliations_organization_id'), ['organization_id'], unique=False)

    op.create_table('membership_plans',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('public_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('internal_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tax_mode', sa.Enum('INCLUSIVE', 'ADDED', name='taxmode'), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('billing_type', sa.Enum('RECURRING', 'ONE_TIME_PACK', 'DROP_IN', name='planbillingtype'), nullable=False),
    sa.Column('cycle_length', sa.Integer(), nullable=True),
    sa.Column('cycle_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('pack_size', sa.Integer(), nullable=True),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('inclusions_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rules_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visibility', sa.Enum('PUBLIC', 'MEMBERS_ONLY', 'INVITE_ONLY', name='planvisibility'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'PAUSED', 'ARCHIVED', name='planstatus'), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('replacement_plan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['replacement_plan_id'], ['membership_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('membership_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membership_plans_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_membership_plans_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_membership_plans_status'), ['status'], unique=False)

    op.create_table('organization_members',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MANAGER', 'TRAINER', 'FRONT_DESK', 'MEMBER', name='role'), nullable=False),
    sa.Column('member_status', sa.Enum('PENDING_PAYMENT', 'PENDING_APPROVAL', 'PENDING_ACTIVATION', 'ACTIVE', 'GRACE', 'EXPIRED', 'FROZEN', 'CANCELLED', 'BANNED', name='memberstatus'), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emergency_contact', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('profile_complete', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('banned', sa.Boolean(), nullable=False),
    sa.Column('fixed_monthly_salary', sa.Float(), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('per_class_rate', sa.Float(), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('commission_window_months', sa.Integer(), nullable=False),
    sa.Column('referred_by_member_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['referred_by_member_id'], ['organization_members.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_members_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_members_member_status'), ['member_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_members_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_members_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_members_user_id'), ['user_id'], unique=False)

    op.create_table('payroll_runs',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'LOCKED', 'FINALIZED', 'PAID', name='payrollstatus'), nullable=False),
    sa.Column('total_gross', sa.Float(), nullable=False),
    sa.Column('total_deductions', sa.Float(), nullable=False),
    sa.Column('total_net', sa.Float(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_runs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_runs_status'), ['status'], unique=False)

    op.create_table('staff_invites',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_invites_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_staff_invites_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_invites_organization_id'), ['organization_id'], unique=False)

    op.create_table('class_sessions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trainer_member_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('booked_count', sa.Integer(), nullable=False),
    sa.Column('trainer_checked_in', sa.Boolean(), nullable=False),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['trainer_member_id'], ['organization_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_sessions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_sessions_starts_at'), ['starts_at'], unique=False)

    op.create_table('pay_advances',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('staff_member_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'APPROVED', 'REJECTED', 'REPAID', name='advancestatus'), nullable=False),
    sa.Column('repayment_per_period', sa.Float(), nullable=False),
    sa.Column('repaid_amount', sa.Float(), nullable=False),
    sa.Column('approved_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['staff_member_id'], ['organization_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pay_advances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pay_advances_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pay_advances_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pay_advances_staff_member_id'), ['staff_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pay_advances_status'), ['status'], unique=False)

    op.create_table('payroll_entries',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payroll_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('staff_member_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fixed', sa.Float(), nullable=False),
    sa.Column('hourly_amount', sa.Float(), nullable=False),
    sa.Column('hours_worked', sa.Float(), nullable=False),
    sa.Column('class_amount', sa.Float(), nullable=False),
    sa.Column('classes_taught', sa.Integer(), nullable=False),
    sa.Column('commission_amount', sa.Float(), nullable=False),
    sa.Column('bonus', sa.Float(), nullable=False),
    sa.Column('deductions', sa.Float(), nullable=False),
    sa.Column('advance_repayment', sa.Float(), nullable=False),
    sa.Column('net', sa.Float(), nullable=False),
    sa.Column('payout_method', sa.Enum('BANK_TRANSFER', 'CASH', 'MOBILE_WALLET', name='payoutmethod'), nullable=False),
    sa.Column('pay_stub_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trainer_confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ),
    sa.ForeignKeyConstraint(['staff_member_id'], ['organization_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payroll_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_entries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_entries_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_entries_payroll_run_id'), ['payroll_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_entries_staff_member_id'), ['staff_member_id'], unique=False)

    op.create_table('shifts',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('staff_member_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), nullable=False),
    sa.Column('checked_out_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('CHECKED_IN', 'CHECKED_OUT', name='shiftstatus'), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.Column('is_overtime', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['staff_member_id'], ['organization_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shifts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shifts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shifts_staff_member_id'), ['staff_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shifts_status'), ['status'], unique=False)

    op.create_table('subscriptions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('member_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'GRACE', 'EXPIRED', 'FROZEN', 'CANCELLED', name='subscriptionstatus'), nullable=False),
    sa.Column('price_snapshot', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('grace_until', sa.DateTime(), nullable=True),
    sa.Column('frozen_until', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('classes_remaining', sa.Integer(), nullable=True),
    sa.Column('stripe_subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['organization_members.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['membership_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_status'), ['status'], unique=False)

    op.create_table('tasks',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assignee_member_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_member_id'], ['organization_members.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_organization_id'), ['organization_id'], unique=False)

    op.create_table('class_bookings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('class_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('member_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('BOOKED', 'ATTENDED', 'CANCELLED', 'NO_SHOW', name='bookingstatus'), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['class_session_id'], ['class_sessions.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['organization_members.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class_bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_bookings_class_session_id'), ['class_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_bookings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_bookings_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_bookings_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_bookings_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_bookings_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_class_bookings_organization_id'))
        batch_op.drop_index(batch_op.f('ix_class_bookings_member_id'))
        batch_op.drop_index(batch_op.f('ix_class_bookings_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_class_bookings_id'))
        batch_op.drop_index(batch_op.f('ix_class_bookings_class_session_id'))

    op.drop_table('class_bookings')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_organization_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_status'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_member_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shifts_status'))
        batch_op.drop_index(batch_op.f('ix_shifts_staff_member_id'))
        batch_op.drop_index(batch_op.f('ix_shifts_organization_id'))
        batch_op.drop_index(batch_op.f('ix_shifts_id'))

    op.drop_table('shifts')
    with op.batch_alter_table('payroll_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_entries_staff_member_id'))
        batch_op.drop_index(batch_op.f('ix_payroll_entries_payroll_run_id'))
        batch_op.drop_index(batch_op.f('ix_payroll_entries_organization_id'))
        batch_op.drop_index(batch_op.f('ix_payroll_entries_id'))

    op.drop_table('payroll_entries')
    with op.batch_alter_table('pay_advances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pay_advances_status'))
        batch_op.drop_index(batch_op.f('ix_pay_advances_staff_member_id'))
        batch_op.drop_index(batch_op.f('ix_pay_advances_organization_id'))
        batch_op.drop_index(batch_op.f('ix_pay_advances_id'))

    op.drop_table('pay_advances')
    with op.batch_alter_table('class_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_sessions_starts_at'))
        batch_op.drop_index(batch_op.f('ix_class_sessions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_class_sessions_id'))

    op.drop_table('class_sessions')
    with op.batch_alter_table('staff_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_invites_organization_id'))
        batch_op.drop_index(batch_op.f('ix_staff_invites_id'))
        batch_op.drop_index(batch_op.f('ix_staff_invites_code'))

    op.drop_table('staff_invites')
    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_runs_status'))
        batch_op.drop_index(batch_op.f('ix_payroll_runs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_payroll_runs_id'))

    op.drop_table('payroll_runs')
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_organization_members_role'))
        batch_op.drop_index(batch_op.f('ix_organization_members_organization_id'))
        batch_op.drop_index(batch_op.f('ix_organization_members_member_status'))
        batch_op.drop_index(batch_op.f('ix_organization_members_id'))

    op.drop_table('organization_members')
    with op.batch_alter_table('membership_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membership_plans_status'))
        batch_op.drop_index(batch_op.f('ix_membership_plans_organization_id'))
        batch_op.drop_index(batch_op.f('ix_membership_plans_id'))

    op.drop_table('membership_plans')
    with op.batch_alter_table('cash_reconciliations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_reconciliations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_cash_reconciliations_id'))
        batch_op.drop_index(batch_op.f('ix_cash_reconciliations_business_date'))

    op.drop_table('cash_reconciliations')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_revoked'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_refresh_token_hash'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_id'))

    op.drop_table('auth_sessions')
    with op.batch_alter_table('verification_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_tokens_purpose'))
        batch_op.drop_index(batch_op.f('ix_verification_tokens_organization_id'))
        batch_op.drop_index(batch_op.f('ix_verification_tokens_id'))
        batch_op.drop_index(batch_op.f('ix_verification_tokens_email'))
        batch_op.drop_index(batch_op.f('ix_verification_tokens_consumed'))
        batch_op.drop_index(batch_op.f('ix_verification_tokens_code_hash'))

    op.drop_table('verification_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('signup_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signup_attempts_status'))
        batch_op.drop_index(batch_op.f('ix_signup_attempts_organization_id'))
        batch_op.drop_index(batch_op.f('ix_signup_attempts_org_code'))
        batch_op.drop_index(batch_op.f('ix_signup_attempts_id'))
        batch_op.drop_index(batch_op.f('ix_signup_attempts_email'))

    op.drop_table('signup_attempts')
    with op.batch_alter_table('receipt_uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipt_uploads_status'))
        batch_op.drop_index(batch_op.f('ix_receipt_uploads_perceptual_hash'))
        batch_op.drop_index(batch_op.f('ix_receipt_uploads_organization_id'))
        batch_op.drop_index(batch_op.f('ix_receipt_uploads_member_id'))
        batch_op.drop_index(batch_op.f('ix_receipt_uploads_id'))

    op.drop_table('receipt_uploads')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_stripe_payment_intent_id'))
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_organization_id'))
        batch_op.drop_index(batch_op.f('ix_payments_kind'))
        batch_op.drop_index(batch_op.f('ix_payments_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_payments_id'))

    op.drop_table('payments')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_org_code'))
        batch_op.drop_index(batch_op.f('ix_organizations_id'))

    op.drop_table('organizations')
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_status'))
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_organization_id'))
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_key'))
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_id'))

    op.drop_table('idempotency_keys')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
