/* ── Thinking words ───────────────────────────────────────────────────────
   Shown while the assistant is working, in place of a static "Thinking…".
   One is chosen at random per turn so the wait reads as activity rather than
   a stuck spinner. A flat list of present participles. */

export const THINKING_WORDS: string[] = [
  "Pondering", "Contemplating", "Considering", "Reasoning", "Deliberating", "Musing",
  "Reflecting", "Meditating", "Ruminating", "Cogitating", "Analyzing", "Evaluating",
  "Assessing", "Appraising", "Weighing", "Judging", "Discerning", "Interpreting",
  "Decoding", "Parsing", "Inspecting", "Examining", "Scrutinizing", "Reviewing",
  "Studying", "Exploring", "Investigating", "Researching", "Probing", "Questioning",
  "Wondering", "Speculating", "Hypothesizing", "Theorizing", "Deducing", "Inferring",
  "Deriving", "Concluding", "Resolving", "Solving", "Calculating", "Computing",
  "Measuring", "Quantifying", "Estimating", "Approximating", "Predicting", "Forecasting",
  "Projecting", "Modeling", "Simulating", "Mapping", "Charting", "Plotting",
  "Tracing", "Tracking", "Following", "Chasing", "Hunting", "Searching",
  "Seeking", "Scanning", "Surveying", "Browsing", "Sifting", "Filtering",
  "Sorting", "Ranking", "Prioritizing", "Ordering", "Arranging", "Organizing",
  "Structuring", "Architecting", "Designing", "Planning", "Scheming", "Strategizing",
  "Blueprinting", "Outlining", "Drafting", "Sketching", "Shaping", "Forming",
  "Molding", "Crafting", "Building", "Assembling", "Constructing", "Composing",
  "Writing", "Rewriting", "Editing", "Polishing", "Refining", "Honing",
  "Sharpening", "Tuning", "Calibrating", "Adjusting", "Tweaking", "Iterating",
  "Looping", "Recursing", "Compounding", "Layering", "Stacking", "Nesting",
  "Weaving", "Braiding", "Interlacing", "Threading", "Stitching", "Knitting",
  "Binding", "Joining", "Linking", "Connecting", "Bridging", "Merging",
  "Blending", "Fusing", "Melding", "Mixing", "Stirring", "Whisking",
  "Folding", "Kneading", "Brewing", "Fermenting", "Distilling", "Purifying",
  "Clarifying", "Crystallizing", "Solidifying", "Hardening", "Setting", "Curing",
  "Tempering", "Annealing", "Forging", "Smelting", "Casting", "Sculpting",
  "Carving", "Whittling", "Chiseling", "Engraving", "Etching", "Painting",
  "Drawing", "Illustrating", "Rendering", "Visualizing", "Depicting", "Portraying",
  "Describing", "Narrating", "Recounting", "Summarizing", "Condensing", "Compressing",
  "Abbreviating", "Trimming", "Pruning", "Clipping", "Cropping", "Paring",
  "Shaving", "Stripping", "Peeling", "Unwrapping", "Unpacking", "Dissecting",
  "Decomposing", "Splitting", "Dividing", "Partitioning", "Segmenting", "Slicing",
  "Dicing", "Chopping", "Grinding", "Milling", "Crushing", "Hammering",
  "Pounding", "Churning", "Spinning", "Twirling", "Swirling", "Rotating",
  "Revolving", "Orbiting", "Circling", "Cycling", "Bouncing", "Rebounding",
  "Refracting", "Diffusing", "Scattering", "Spreading", "Dispersing", "Distributing",
  "Allocating", "Assigning", "Delegating", "Routing", "Directing", "Guiding",
  "Steering", "Navigating", "Piloting", "Sailing", "Cruising", "Voyaging",
  "Journeying", "Traveling", "Wandering", "Roaming", "Drifting", "Floating",
  "Gliding", "Soaring", "Flying", "Hovering", "Landing", "Anchoring",
  "Mooring", "Docking", "Settling", "Resting", "Pausing", "Lingering",
  "Loitering", "Dawdling", "Stalling", "Hesitating", "Oscillating", "Vacillating",
  "Wavering", "Fluctuating", "Vibrating", "Pulsing", "Throbbing", "Ticking",
  "Chiming", "Ringing", "Resounding", "Echoing", "Resonating", "Reverberating",
  "Humming", "Buzzing", "Whirring", "Purring", "Rumbling", "Murmuring",
  "Whispering", "Rustling", "Crackling", "Sparkling", "Glinting", "Gleaming",
  "Glistening", "Shimmering", "Glowing", "Radiating", "Beaming", "Shining",
  "Brightening", "Illuminating", "Lighting", "Kindling", "Igniting", "Sparking",
  "Flaming", "Burning", "Smoldering", "Warming", "Heating", "Melting",
  "Thawing", "Softening", "Soothing", "Calming", "Quieting", "Hushing",
  "Silencing", "Muffling", "Damping", "Muting", "Dimming", "Fading",
  "Dissolving", "Evaporating", "Vaporizing", "Precipitating", "Raining", "Pouring",
  "Drizzling", "Misting", "Fogging", "Clouding", "Clearing", "Dawning",
  "Rising", "Ascending", "Climbing", "Scaling", "Mounting", "Surging",
  "Swelling", "Growing", "Sprouting", "Budding", "Blooming", "Flowering",
  "Blossoming", "Ripening", "Maturing", "Developing", "Evolving", "Transforming",
  "Metamorphosing", "Mutating", "Adapting", "Acclimating", "Assimilating", "Integrating",
  "Unifying", "Harmonizing", "Balancing", "Equalizing", "Stabilizing", "Grounding",
  "Centering", "Focusing", "Concentrating", "Attending", "Noticing", "Observing",
  "Watching", "Glimpsing", "Peeking", "Peering", "Gazing", "Staring",
  "Beholding", "Witnessing", "Perceiving", "Sensing", "Feeling", "Touching",
  "Grasping", "Holding", "Clutching", "Cradling", "Embracing", "Welcoming",
  "Greeting", "Encountering", "Discovering", "Uncovering", "Revealing", "Exposing",
  "Disclosing", "Unveiling", "Unearthing", "Excavating", "Digging", "Drilling",
  "Boring", "Tunneling", "Burrowing", "Delving", "Diving", "Plunging",
  "Submerging", "Immersing", "Soaking", "Saturating", "Steeping", "Marinating",
  "Seasoning", "Spicing", "Flavoring", "Savoring", "Tasting", "Relishing",
  "Enjoying", "Cherishing", "Treasuring", "Valuing", "Appreciating", "Honoring",
  "Celebrating", "Commemorating", "Marking", "Noting", "Recording", "Logging",
  "Documenting", "Cataloging", "Archiving", "Storing", "Saving", "Preserving",
  "Conserving", "Protecting", "Guarding", "Shielding", "Sheltering", "Nurturing",
  "Fostering", "Cultivating", "Planting", "Seeding", "Watering", "Nourishing",
  "Feeding", "Fueling", "Powering", "Energizing", "Invigorating", "Refreshing",
  "Renewing", "Restoring", "Repairing", "Mending", "Healing", "Patching",
  "Fixing", "Correcting", "Rectifying", "Remedying", "Untangling", "Unscrambling",
  "Unraveling", "Deciphering", "Unlocking", "Opening", "Unfolding", "Expanding",
  "Extending", "Stretching", "Reaching", "Spanning", "Covering", "Encompassing",
  "Surrounding", "Encircling", "Wrapping", "Enclosing", "Containing", "Keeping",
  "Maintaining", "Sustaining", "Supporting", "Upholding", "Bolstering", "Reinforcing",
  "Strengthening", "Fortifying", "Toughening", "Steadying", "Securing", "Fastening",
  "Lacing", "Netting", "Trapping", "Catching", "Snaring", "Hooking",
  "Luring", "Attracting", "Pulling", "Tugging", "Hauling", "Dragging",
  "Lifting", "Raising", "Hoisting", "Elevating", "Boosting", "Promoting",
  "Advancing", "Progressing", "Shifting", "Transferring", "Transporting", "Carrying",
  "Conveying", "Delivering", "Transmitting", "Broadcasting", "Signaling", "Gesturing",
  "Motioning", "Nodding", "Winking", "Smiling", "Grinning", "Laughing",
  "Chuckling", "Giggling", "Cheering", "Applauding", "Clapping", "Dancing",
  "Swaying", "Rocking", "Rolling", "Tumbling", "Flipping", "Vaulting",
  "Leaping", "Jumping", "Hopping", "Skipping", "Bounding", "Sprinting",
  "Running", "Jogging", "Walking", "Strolling", "Ambling", "Sauntering",
  "Marching", "Parading", "Striding", "Stepping",
];

/** A random present participle for the working indicator. */
export function randomThinkingWord(): string {
  return THINKING_WORDS[Math.floor(Math.random() * THINKING_WORDS.length)];
}
